version: '3.1'

services:

  db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    container_name: db